//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CustID"/>
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DeliveryAddr"/>
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Note"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AbsLNameNum"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AbsFNameNum"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Title"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Age"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Gender"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Smoking"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CitizenshipCountry"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PassportNum"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PassportCountry"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DOB"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Occupation"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SSN"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Addr1"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Addr2"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}City"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}StateProvince"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ZIPPostal"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Country"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}VisaCountry"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}VISAID"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}VisaExpDt"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}VISAText"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TypeInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}VarLenQual" minOccurs="0"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CCQual" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "custID",
    "deliveryAddr",
    "note",
    "absLNameNum",
    "absFNameNum",
    "title",
    "age",
    "gender",
    "smoking",
    "citizenshipCountry",
    "passportNum",
    "passportCountry",
    "dob",
    "occupation",
    "ssn",
    "addr1",
    "addr2",
    "city",
    "stateProvince",
    "zipPostal",
    "country",
    "visaCountry",
    "visaid",
    "visaExpDt",
    "visaText",
    "typeInd",
    "varLenQual",
    "ccQual"
})
@XmlRootElement(name = "AddChgQual")
public class AddChgQual
    implements Serializable
{

    @XmlElement(name = "CustID")
    protected CustID custID;
    @XmlElement(name = "DeliveryAddr")
    protected String deliveryAddr;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "AbsLNameNum")
    protected String absLNameNum;
    @XmlElement(name = "AbsFNameNum")
    protected String absFNameNum;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "Age")
    protected String age;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "Smoking")
    protected String smoking;
    @XmlElement(name = "CitizenshipCountry")
    protected String citizenshipCountry;
    @XmlElement(name = "PassportNum")
    protected String passportNum;
    @XmlElement(name = "PassportCountry")
    protected String passportCountry;
    @XmlElement(name = "DOB")
    protected String dob;
    @XmlElement(name = "Occupation")
    protected String occupation;
    @XmlElement(name = "SSN")
    protected String ssn;
    @XmlElement(name = "Addr1")
    protected String addr1;
    @XmlElement(name = "Addr2")
    protected String addr2;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "StateProvince")
    protected String stateProvince;
    @XmlElement(name = "ZIPPostal")
    protected String zipPostal;
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "VisaCountry")
    protected String visaCountry;
    @XmlElement(name = "VISAID")
    protected String visaid;
    @XmlElement(name = "VisaExpDt")
    protected String visaExpDt;
    @XmlElement(name = "VISAText")
    protected String visaText;
    @XmlElement(name = "TypeInd")
    protected String typeInd;
    @XmlElement(name = "VarLenQual")
    protected VarLenQual varLenQual;
    @XmlElement(name = "CCQual")
    protected CCQual ccQual;

    /**
     * Gets the value of the custID property.
     * 
     * @return
     *     possible object is
     *     {@link CustID }
     *     
     */
    public CustID getCustID() {
        return custID;
    }

    /**
     * Sets the value of the custID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustID }
     *     
     */
    public void setCustID(CustID value) {
        this.custID = value;
    }

    /**
     * Gets the value of the deliveryAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryAddr() {
        return deliveryAddr;
    }

    /**
     * Sets the value of the deliveryAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryAddr(String value) {
        this.deliveryAddr = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the absLNameNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsLNameNum() {
        return absLNameNum;
    }

    /**
     * Sets the value of the absLNameNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsLNameNum(String value) {
        this.absLNameNum = value;
    }

    /**
     * Gets the value of the absFNameNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsFNameNum() {
        return absFNameNum;
    }

    /**
     * Sets the value of the absFNameNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsFNameNum(String value) {
        this.absFNameNum = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the smoking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmoking() {
        return smoking;
    }

    /**
     * Sets the value of the smoking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmoking(String value) {
        this.smoking = value;
    }

    /**
     * Gets the value of the citizenshipCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitizenshipCountry() {
        return citizenshipCountry;
    }

    /**
     * Sets the value of the citizenshipCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitizenshipCountry(String value) {
        this.citizenshipCountry = value;
    }

    /**
     * Gets the value of the passportNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportNum() {
        return passportNum;
    }

    /**
     * Sets the value of the passportNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportNum(String value) {
        this.passportNum = value;
    }

    /**
     * Gets the value of the passportCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportCountry() {
        return passportCountry;
    }

    /**
     * Sets the value of the passportCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportCountry(String value) {
        this.passportCountry = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOB(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the addr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * Sets the value of the addr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr1(String value) {
        this.addr1 = value;
    }

    /**
     * Gets the value of the addr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * Sets the value of the addr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr2(String value) {
        this.addr2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the stateProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * Sets the value of the stateProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateProvince(String value) {
        this.stateProvince = value;
    }

    /**
     * Gets the value of the zipPostal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPPostal() {
        return zipPostal;
    }

    /**
     * Sets the value of the zipPostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPPostal(String value) {
        this.zipPostal = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the visaCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaCountry() {
        return visaCountry;
    }

    /**
     * Sets the value of the visaCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaCountry(String value) {
        this.visaCountry = value;
    }

    /**
     * Gets the value of the visaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISAID() {
        return visaid;
    }

    /**
     * Sets the value of the visaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISAID(String value) {
        this.visaid = value;
    }

    /**
     * Gets the value of the visaExpDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaExpDt() {
        return visaExpDt;
    }

    /**
     * Sets the value of the visaExpDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaExpDt(String value) {
        this.visaExpDt = value;
    }

    /**
     * Gets the value of the visaText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISAText() {
        return visaText;
    }

    /**
     * Sets the value of the visaText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISAText(String value) {
        this.visaText = value;
    }

    /**
     * Gets the value of the typeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeInd() {
        return typeInd;
    }

    /**
     * Sets the value of the typeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeInd(String value) {
        this.typeInd = value;
    }

    /**
     * Gets the value of the varLenQual property.
     * 
     * @return
     *     possible object is
     *     {@link VarLenQual }
     *     
     */
    public VarLenQual getVarLenQual() {
        return varLenQual;
    }

    /**
     * Sets the value of the varLenQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link VarLenQual }
     *     
     */
    public void setVarLenQual(VarLenQual value) {
        this.varLenQual = value;
    }

    /**
     * Gets the value of the ccQual property.
     * 
     * @return
     *     possible object is
     *     {@link CCQual }
     *     
     */
    public CCQual getCCQual() {
        return ccQual;
    }

    /**
     * Sets the value of the ccQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCQual }
     *     
     */
    public void setCCQual(CCQual value) {
        this.ccQual = value;
    }

}
