//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}UniqueKey"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QuoteNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareComponentNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PriceUnitNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare1"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare2"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare3"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NoRsvn"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnOnlyIfTk"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnAnyTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnHrs"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnDays"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnMonths"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnEarliestTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnLatestTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnWaived"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnDataExists"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnEndItem"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare4"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare5"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare6"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare7"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare8"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkEarliestTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkLatestTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkRsvnHrs"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkRsvnDays"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkRsvnMonths"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkStartHrs"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkStartDays"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkStartMonths"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkWaived"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkAnyTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkEndItem"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare9"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare10"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvRsvnTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkRsvnTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdvTkStartTm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueKey",
    "quoteNum",
    "fareComponentNum",
    "priceUnitNum",
    "spare1",
    "spare2",
    "spare3",
    "noRsvn",
    "advRsvnOnlyIfTk",
    "advRsvnAnyTm",
    "advRsvnHrs",
    "advRsvnDays",
    "advRsvnMonths",
    "advRsvnEarliestTm",
    "advRsvnLatestTm",
    "advRsvnWaived",
    "advRsvnDataExists",
    "advRsvnEndItem",
    "spare4",
    "spare5",
    "spare6",
    "spare7",
    "spare8",
    "advTkEarliestTm",
    "advTkLatestTm",
    "advTkRsvnHrs",
    "advTkRsvnDays",
    "advTkRsvnMonths",
    "advTkStartHrs",
    "advTkStartDays",
    "advTkStartMonths",
    "advTkWaived",
    "advTkAnyTm",
    "advTkEndItem",
    "spare9",
    "spare10",
    "advRsvnTm",
    "advTkRsvnTm",
    "advTkStartTm"
})
@XmlRootElement(name = "AdvRsvnTktRules")
public class AdvRsvnTktRules
    implements Serializable
{

    @XmlElement(name = "UniqueKey", required = true)
    protected String uniqueKey;
    @XmlElement(name = "QuoteNum", required = true)
    protected String quoteNum;
    @XmlElement(name = "FareComponentNum", required = true)
    protected String fareComponentNum;
    @XmlElement(name = "PriceUnitNum", required = true)
    protected String priceUnitNum;
    @XmlElement(name = "Spare1", required = true)
    protected String spare1;
    @XmlElement(name = "Spare2", required = true)
    protected String spare2;
    @XmlElement(name = "Spare3", required = true)
    protected String spare3;
    @XmlElement(name = "NoRsvn", required = true)
    protected String noRsvn;
    @XmlElement(name = "AdvRsvnOnlyIfTk", required = true)
    protected String advRsvnOnlyIfTk;
    @XmlElement(name = "AdvRsvnAnyTm", required = true)
    protected String advRsvnAnyTm;
    @XmlElement(name = "AdvRsvnHrs", required = true)
    protected String advRsvnHrs;
    @XmlElement(name = "AdvRsvnDays", required = true)
    protected String advRsvnDays;
    @XmlElement(name = "AdvRsvnMonths", required = true)
    protected String advRsvnMonths;
    @XmlElement(name = "AdvRsvnEarliestTm", required = true)
    protected String advRsvnEarliestTm;
    @XmlElement(name = "AdvRsvnLatestTm", required = true)
    protected String advRsvnLatestTm;
    @XmlElement(name = "AdvRsvnWaived", required = true)
    protected String advRsvnWaived;
    @XmlElement(name = "AdvRsvnDataExists", required = true)
    protected String advRsvnDataExists;
    @XmlElement(name = "AdvRsvnEndItem", required = true)
    protected String advRsvnEndItem;
    @XmlElement(name = "Spare4", required = true)
    protected String spare4;
    @XmlElement(name = "Spare5", required = true)
    protected String spare5;
    @XmlElement(name = "Spare6", required = true)
    protected String spare6;
    @XmlElement(name = "Spare7", required = true)
    protected String spare7;
    @XmlElement(name = "Spare8", required = true)
    protected String spare8;
    @XmlElement(name = "AdvTkEarliestTm", required = true)
    protected String advTkEarliestTm;
    @XmlElement(name = "AdvTkLatestTm", required = true)
    protected String advTkLatestTm;
    @XmlElement(name = "AdvTkRsvnHrs", required = true)
    protected String advTkRsvnHrs;
    @XmlElement(name = "AdvTkRsvnDays", required = true)
    protected String advTkRsvnDays;
    @XmlElement(name = "AdvTkRsvnMonths", required = true)
    protected String advTkRsvnMonths;
    @XmlElement(name = "AdvTkStartHrs", required = true)
    protected String advTkStartHrs;
    @XmlElement(name = "AdvTkStartDays", required = true)
    protected String advTkStartDays;
    @XmlElement(name = "AdvTkStartMonths", required = true)
    protected String advTkStartMonths;
    @XmlElement(name = "AdvTkWaived", required = true)
    protected String advTkWaived;
    @XmlElement(name = "AdvTkAnyTm", required = true)
    protected String advTkAnyTm;
    @XmlElement(name = "AdvTkEndItem", required = true)
    protected String advTkEndItem;
    @XmlElement(name = "Spare9", required = true)
    protected String spare9;
    @XmlElement(name = "Spare10", required = true)
    protected String spare10;
    @XmlElement(name = "AdvRsvnTm", required = true)
    protected String advRsvnTm;
    @XmlElement(name = "AdvTkRsvnTm", required = true)
    protected String advTkRsvnTm;
    @XmlElement(name = "AdvTkStartTm", required = true)
    protected String advTkStartTm;

    /**
     * Gets the value of the uniqueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKey() {
        return uniqueKey;
    }

    /**
     * Sets the value of the uniqueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKey(String value) {
        this.uniqueKey = value;
    }

    /**
     * Gets the value of the quoteNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteNum() {
        return quoteNum;
    }

    /**
     * Sets the value of the quoteNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteNum(String value) {
        this.quoteNum = value;
    }

    /**
     * Gets the value of the fareComponentNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareComponentNum() {
        return fareComponentNum;
    }

    /**
     * Sets the value of the fareComponentNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareComponentNum(String value) {
        this.fareComponentNum = value;
    }

    /**
     * Gets the value of the priceUnitNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceUnitNum() {
        return priceUnitNum;
    }

    /**
     * Sets the value of the priceUnitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceUnitNum(String value) {
        this.priceUnitNum = value;
    }

    /**
     * Gets the value of the spare1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * Sets the value of the spare1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare1(String value) {
        this.spare1 = value;
    }

    /**
     * Gets the value of the spare2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * Sets the value of the spare2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare2(String value) {
        this.spare2 = value;
    }

    /**
     * Gets the value of the spare3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * Sets the value of the spare3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare3(String value) {
        this.spare3 = value;
    }

    /**
     * Gets the value of the noRsvn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoRsvn() {
        return noRsvn;
    }

    /**
     * Sets the value of the noRsvn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoRsvn(String value) {
        this.noRsvn = value;
    }

    /**
     * Gets the value of the advRsvnOnlyIfTk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnOnlyIfTk() {
        return advRsvnOnlyIfTk;
    }

    /**
     * Sets the value of the advRsvnOnlyIfTk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnOnlyIfTk(String value) {
        this.advRsvnOnlyIfTk = value;
    }

    /**
     * Gets the value of the advRsvnAnyTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnAnyTm() {
        return advRsvnAnyTm;
    }

    /**
     * Sets the value of the advRsvnAnyTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnAnyTm(String value) {
        this.advRsvnAnyTm = value;
    }

    /**
     * Gets the value of the advRsvnHrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnHrs() {
        return advRsvnHrs;
    }

    /**
     * Sets the value of the advRsvnHrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnHrs(String value) {
        this.advRsvnHrs = value;
    }

    /**
     * Gets the value of the advRsvnDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnDays() {
        return advRsvnDays;
    }

    /**
     * Sets the value of the advRsvnDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnDays(String value) {
        this.advRsvnDays = value;
    }

    /**
     * Gets the value of the advRsvnMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnMonths() {
        return advRsvnMonths;
    }

    /**
     * Sets the value of the advRsvnMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnMonths(String value) {
        this.advRsvnMonths = value;
    }

    /**
     * Gets the value of the advRsvnEarliestTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnEarliestTm() {
        return advRsvnEarliestTm;
    }

    /**
     * Sets the value of the advRsvnEarliestTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnEarliestTm(String value) {
        this.advRsvnEarliestTm = value;
    }

    /**
     * Gets the value of the advRsvnLatestTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnLatestTm() {
        return advRsvnLatestTm;
    }

    /**
     * Sets the value of the advRsvnLatestTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnLatestTm(String value) {
        this.advRsvnLatestTm = value;
    }

    /**
     * Gets the value of the advRsvnWaived property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnWaived() {
        return advRsvnWaived;
    }

    /**
     * Sets the value of the advRsvnWaived property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnWaived(String value) {
        this.advRsvnWaived = value;
    }

    /**
     * Gets the value of the advRsvnDataExists property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnDataExists() {
        return advRsvnDataExists;
    }

    /**
     * Sets the value of the advRsvnDataExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnDataExists(String value) {
        this.advRsvnDataExists = value;
    }

    /**
     * Gets the value of the advRsvnEndItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnEndItem() {
        return advRsvnEndItem;
    }

    /**
     * Sets the value of the advRsvnEndItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnEndItem(String value) {
        this.advRsvnEndItem = value;
    }

    /**
     * Gets the value of the spare4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare4() {
        return spare4;
    }

    /**
     * Sets the value of the spare4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare4(String value) {
        this.spare4 = value;
    }

    /**
     * Gets the value of the spare5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare5() {
        return spare5;
    }

    /**
     * Sets the value of the spare5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare5(String value) {
        this.spare5 = value;
    }

    /**
     * Gets the value of the spare6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare6() {
        return spare6;
    }

    /**
     * Sets the value of the spare6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare6(String value) {
        this.spare6 = value;
    }

    /**
     * Gets the value of the spare7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare7() {
        return spare7;
    }

    /**
     * Sets the value of the spare7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare7(String value) {
        this.spare7 = value;
    }

    /**
     * Gets the value of the spare8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare8() {
        return spare8;
    }

    /**
     * Sets the value of the spare8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare8(String value) {
        this.spare8 = value;
    }

    /**
     * Gets the value of the advTkEarliestTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkEarliestTm() {
        return advTkEarliestTm;
    }

    /**
     * Sets the value of the advTkEarliestTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkEarliestTm(String value) {
        this.advTkEarliestTm = value;
    }

    /**
     * Gets the value of the advTkLatestTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkLatestTm() {
        return advTkLatestTm;
    }

    /**
     * Sets the value of the advTkLatestTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkLatestTm(String value) {
        this.advTkLatestTm = value;
    }

    /**
     * Gets the value of the advTkRsvnHrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkRsvnHrs() {
        return advTkRsvnHrs;
    }

    /**
     * Sets the value of the advTkRsvnHrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkRsvnHrs(String value) {
        this.advTkRsvnHrs = value;
    }

    /**
     * Gets the value of the advTkRsvnDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkRsvnDays() {
        return advTkRsvnDays;
    }

    /**
     * Sets the value of the advTkRsvnDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkRsvnDays(String value) {
        this.advTkRsvnDays = value;
    }

    /**
     * Gets the value of the advTkRsvnMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkRsvnMonths() {
        return advTkRsvnMonths;
    }

    /**
     * Sets the value of the advTkRsvnMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkRsvnMonths(String value) {
        this.advTkRsvnMonths = value;
    }

    /**
     * Gets the value of the advTkStartHrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkStartHrs() {
        return advTkStartHrs;
    }

    /**
     * Sets the value of the advTkStartHrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkStartHrs(String value) {
        this.advTkStartHrs = value;
    }

    /**
     * Gets the value of the advTkStartDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkStartDays() {
        return advTkStartDays;
    }

    /**
     * Sets the value of the advTkStartDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkStartDays(String value) {
        this.advTkStartDays = value;
    }

    /**
     * Gets the value of the advTkStartMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkStartMonths() {
        return advTkStartMonths;
    }

    /**
     * Sets the value of the advTkStartMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkStartMonths(String value) {
        this.advTkStartMonths = value;
    }

    /**
     * Gets the value of the advTkWaived property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkWaived() {
        return advTkWaived;
    }

    /**
     * Sets the value of the advTkWaived property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkWaived(String value) {
        this.advTkWaived = value;
    }

    /**
     * Gets the value of the advTkAnyTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkAnyTm() {
        return advTkAnyTm;
    }

    /**
     * Sets the value of the advTkAnyTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkAnyTm(String value) {
        this.advTkAnyTm = value;
    }

    /**
     * Gets the value of the advTkEndItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkEndItem() {
        return advTkEndItem;
    }

    /**
     * Sets the value of the advTkEndItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkEndItem(String value) {
        this.advTkEndItem = value;
    }

    /**
     * Gets the value of the spare9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare9() {
        return spare9;
    }

    /**
     * Sets the value of the spare9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare9(String value) {
        this.spare9 = value;
    }

    /**
     * Gets the value of the spare10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare10() {
        return spare10;
    }

    /**
     * Sets the value of the spare10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare10(String value) {
        this.spare10 = value;
    }

    /**
     * Gets the value of the advRsvnTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvRsvnTm() {
        return advRsvnTm;
    }

    /**
     * Sets the value of the advRsvnTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvRsvnTm(String value) {
        this.advRsvnTm = value;
    }

    /**
     * Gets the value of the advTkRsvnTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkRsvnTm() {
        return advTkRsvnTm;
    }

    /**
     * Sets the value of the advTkRsvnTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkRsvnTm(String value) {
        this.advTkRsvnTm = value;
    }

    /**
     * Gets the value of the advTkStartTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvTkStartTm() {
        return advTkStartTm;
    }

    /**
     * Sets the value of the advTkStartTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvTkStartTm(String value) {
        this.advTkStartTm = value;
    }

}
