//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AgncySimlrNameMatch"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Control"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ErrText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agncySimlrNameMatch",
    "control",
    "errText"
})
@XmlRootElement(name = "AgncySimlrName")
public class AgncySimlrName implements Serializable
{

    @XmlElement(name = "AgncySimlrNameMatch", required = true)
    protected AgncySimlrNameMatch agncySimlrNameMatch;
    @XmlElement(name = "Control", required = true)
    protected Control control;
    @XmlElement(name = "ErrText", required = true)
    protected ErrText errText;

    /**
     * Gets the value of the agncySimlrNameMatch property.
     * 
     * @return
     *     possible object is
     *     {@link AgncySimlrNameMatch }
     *     
     */
    public AgncySimlrNameMatch getAgncySimlrNameMatch() {
        return agncySimlrNameMatch;
    }

    /**
     * Sets the value of the agncySimlrNameMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgncySimlrNameMatch }
     *     
     */
    public void setAgncySimlrNameMatch(AgncySimlrNameMatch value) {
        this.agncySimlrNameMatch = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link Control }
     *     
     */
    public Control getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Control }
     *     
     */
    public void setControl(Control value) {
        this.control = value;
    }

    /**
     * Gets the value of the errText property.
     * 
     * @return
     *     possible object is
     *     {@link ErrText }
     *     
     */
    public ErrText getErrText() {
        return errText;
    }

    /**
     * Sets the value of the errText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrText }
     *     
     */
    public void setErrText(ErrText value) {
        this.errText = value;
    }

}
