//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Sys"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Processor"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}GrpModeActivatedInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AAAAreaAry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sys",
    "processor",
    "grpModeActivatedInd",
    "aaaAreaAry"
})
@XmlRootElement(name = "AreaInfoResp")
public class AreaInfoResp
    implements Serializable
{

    @XmlElement(name = "Sys", required = true)
    protected String sys;
    @XmlElement(name = "Processor", required = true)
    protected String processor;
    @XmlElement(name = "GrpModeActivatedInd", required = true)
    protected String grpModeActivatedInd;
    @XmlElement(name = "AAAAreaAry", required = true)
    protected AAAAreaAry aaaAreaAry;

    /**
     * Gets the value of the sys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSys() {
        return sys;
    }

    /**
     * Sets the value of the sys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSys(String value) {
        this.sys = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessor(String value) {
        this.processor = value;
    }

    /**
     * Gets the value of the grpModeActivatedInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrpModeActivatedInd() {
        return grpModeActivatedInd;
    }

    /**
     * Sets the value of the grpModeActivatedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrpModeActivatedInd(String value) {
        this.grpModeActivatedInd = value;
    }

    /**
     * Gets the value of the aaaAreaAry property.
     * 
     * @return
     *     possible object is
     *     {@link AAAAreaAry }
     *     
     */
    public AAAAreaAry getAAAAreaAry() {
        return aaaAreaAry;
    }

    /**
     * Sets the value of the aaaAreaAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAAAreaAry }
     *     
     */
    public void setAAAAreaAry(AAAAreaAry value) {
        this.aaaAreaAry = value;
    }

}
