//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EditTypeInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AirQual"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CarQual"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}HtlQual"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AssocRmkTypeQual"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "editTypeInd",
    "airQual",
    "carQual",
    "htlQual",
    "assocRmkTypeQual"
})
@XmlRootElement(name = "AssocRmkQual")
public class AssocRmkQual
    implements Serializable
{

    @XmlElement(name = "EditTypeInd", required = true)
    protected String editTypeInd;
    @XmlElement(name = "AirQual", required = true)
    protected AirQual airQual;
    @XmlElement(name = "CarQual", required = true)
    protected CarQual carQual;
    @XmlElement(name = "HtlQual", required = true)
    protected HtlQual htlQual;
    @XmlElement(name = "AssocRmkTypeQual", required = true)
    protected AssocRmkTypeQual assocRmkTypeQual;

    /**
     * Gets the value of the editTypeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditTypeInd() {
        return editTypeInd;
    }

    /**
     * Sets the value of the editTypeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditTypeInd(String value) {
        this.editTypeInd = value;
    }

    /**
     * Gets the value of the airQual property.
     * 
     * @return
     *     possible object is
     *     {@link AirQual }
     *     
     */
    public AirQual getAirQual() {
        return airQual;
    }

    /**
     * Sets the value of the airQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirQual }
     *     
     */
    public void setAirQual(AirQual value) {
        this.airQual = value;
    }

    /**
     * Gets the value of the carQual property.
     * 
     * @return
     *     possible object is
     *     {@link CarQual }
     *     
     */
    public CarQual getCarQual() {
        return carQual;
    }

    /**
     * Sets the value of the carQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarQual }
     *     
     */
    public void setCarQual(CarQual value) {
        this.carQual = value;
    }

    /**
     * Gets the value of the htlQual property.
     * 
     * @return
     *     possible object is
     *     {@link HtlQual }
     *     
     */
    public HtlQual getHtlQual() {
        return htlQual;
    }

    /**
     * Sets the value of the htlQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link HtlQual }
     *     
     */
    public void setHtlQual(HtlQual value) {
        this.htlQual = value;
    }

    /**
     * Gets the value of the assocRmkTypeQual property.
     * 
     * @return
     *     possible object is
     *     {@link AssocRmkTypeQual }
     *     
     */
    public AssocRmkTypeQual getAssocRmkTypeQual() {
        return assocRmkTypeQual;
    }

    /**
     * Sets the value of the assocRmkTypeQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssocRmkTypeQual }
     *     
     */
    public void setAssocRmkTypeQual(AssocRmkTypeQual value) {
        this.assocRmkTypeQual = value;
    }

}
