//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EndTransactResponse"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EndTransactMessage"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "endTransactResponse",
    "endTransactMessage"
})
@XmlRootElement(name = "EndTransaction")
public class EndTransaction implements Serializable
{

    @XmlElement(name = "EndTransactResponse", required = true)
    protected EndTransactResponse endTransactResponse;
    @XmlElement(name = "EndTransactMessage", required = true)
    protected EndTransactMessage endTransactMessage;

    /**
     * Gets the value of the endTransactResponse property.
     * 
     * @return
     *     possible object is
     *     {@link EndTransactResponse }
     *     
     */
    public EndTransactResponse getEndTransactResponse() {
        return endTransactResponse;
    }

    /**
     * Sets the value of the endTransactResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndTransactResponse }
     *     
     */
    public void setEndTransactResponse(EndTransactResponse value) {
        this.endTransactResponse = value;
    }

    /**
     * Gets the value of the endTransactMessage property.
     * 
     * @return
     *     possible object is
     *     {@link EndTransactMessage }
     *     
     */
    public EndTransactMessage getEndTransactMessage() {
        return endTransactMessage;
    }

    /**
     * Sets the value of the endTransactMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndTransactMessage }
     *     
     */
    public void setEndTransactMessage(EndTransactMessage value) {
        this.endTransactMessage = value;
    }

}
