//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}UniqueKey"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}InternalUseonly"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QuoteNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AirV"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PrivateFareOverride"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FlatFareQuoted"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DiscAirlinePFQuoted"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PublishedAirlinePFQuoted"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}IntUseOnly"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PublishedFIC"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdditionalPFInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueKey",
    "internalUseonly",
    "quoteNum",
    "fareNum",
    "airV",
    "privateFareOverride",
    "flatFareQuoted",
    "discAirlinePFQuoted",
    "publishedAirlinePFQuoted",
    "intUseOnly",
    "publishedFIC",
    "additionalPFInfo"
})
@XmlRootElement(name = "EnhancedPrivateFare")
public class EnhancedPrivateFare
    implements Serializable
{

    @XmlElement(name = "UniqueKey", required = true)
    protected String uniqueKey;
    @XmlElement(name = "InternalUseonly", required = true)
    protected String internalUseonly;
    @XmlElement(name = "QuoteNum", required = true)
    protected String quoteNum;
    @XmlElement(name = "FareNum", required = true)
    protected String fareNum;
    @XmlElement(name = "AirV", required = true)
    protected String airV;
    @XmlElement(name = "PrivateFareOverride", required = true)
    protected String privateFareOverride;
    @XmlElement(name = "FlatFareQuoted", required = true)
    protected String flatFareQuoted;
    @XmlElement(name = "DiscAirlinePFQuoted", required = true)
    protected String discAirlinePFQuoted;
    @XmlElement(name = "PublishedAirlinePFQuoted", required = true)
    protected String publishedAirlinePFQuoted;
    @XmlElement(name = "IntUseOnly", required = true)
    protected String intUseOnly;
    @XmlElement(name = "PublishedFIC", required = true)
    protected String publishedFIC;
    @XmlElement(name = "AdditionalPFInfo", required = true)
    protected String additionalPFInfo;

    /**
     * Gets the value of the uniqueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKey() {
        return uniqueKey;
    }

    /**
     * Sets the value of the uniqueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKey(String value) {
        this.uniqueKey = value;
    }

    /**
     * Gets the value of the internalUseonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalUseonly() {
        return internalUseonly;
    }

    /**
     * Sets the value of the internalUseonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalUseonly(String value) {
        this.internalUseonly = value;
    }

    /**
     * Gets the value of the quoteNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteNum() {
        return quoteNum;
    }

    /**
     * Sets the value of the quoteNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteNum(String value) {
        this.quoteNum = value;
    }

    /**
     * Gets the value of the fareNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareNum() {
        return fareNum;
    }

    /**
     * Sets the value of the fareNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareNum(String value) {
        this.fareNum = value;
    }

    /**
     * Gets the value of the airV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirV() {
        return airV;
    }

    /**
     * Sets the value of the airV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirV(String value) {
        this.airV = value;
    }

    /**
     * Gets the value of the privateFareOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateFareOverride() {
        return privateFareOverride;
    }

    /**
     * Sets the value of the privateFareOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateFareOverride(String value) {
        this.privateFareOverride = value;
    }

    /**
     * Gets the value of the flatFareQuoted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatFareQuoted() {
        return flatFareQuoted;
    }

    /**
     * Sets the value of the flatFareQuoted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatFareQuoted(String value) {
        this.flatFareQuoted = value;
    }

    /**
     * Gets the value of the discAirlinePFQuoted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscAirlinePFQuoted() {
        return discAirlinePFQuoted;
    }

    /**
     * Sets the value of the discAirlinePFQuoted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscAirlinePFQuoted(String value) {
        this.discAirlinePFQuoted = value;
    }

    /**
     * Gets the value of the publishedAirlinePFQuoted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishedAirlinePFQuoted() {
        return publishedAirlinePFQuoted;
    }

    /**
     * Sets the value of the publishedAirlinePFQuoted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishedAirlinePFQuoted(String value) {
        this.publishedAirlinePFQuoted = value;
    }

    /**
     * Gets the value of the intUseOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntUseOnly() {
        return intUseOnly;
    }

    /**
     * Sets the value of the intUseOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntUseOnly(String value) {
        this.intUseOnly = value;
    }

    /**
     * Gets the value of the publishedFIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishedFIC() {
        return publishedFIC;
    }

    /**
     * Sets the value of the publishedFIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishedFIC(String value) {
        this.publishedFIC = value;
    }

    /**
     * Gets the value of the additionalPFInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalPFInfo() {
        return additionalPFInfo;
    }

    /**
     * Sets the value of the additionalPFInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalPFInfo(String value) {
        this.additionalPFInfo = value;
    }

}
