//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Name"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FirstStockCtrl"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}LastStockCtrl"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AirV"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FirstTkNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}LastTkNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ItinInvNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Crncy" minOccurs="0"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Currency" minOccurs="0"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Fare"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TkType"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Dt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Tm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}VndIssueDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CurHistoryInd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "firstStockCtrl",
    "lastStockCtrl",
    "airV",
    "firstTkNum",
    "lastTkNum",
    "itinInvNum",
    "crncy",
    "currency",
    "fare",
    "tkType",
    "dt",
    "tm",
    "vndIssueDt",
    "curHistoryInd"
})
@XmlRootElement(name = "ETicketNum")
public class ETicketNum
    implements Serializable
{

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "FirstStockCtrl", required = true)
    protected String firstStockCtrl;
    @XmlElement(name = "LastStockCtrl", required = true)
    protected String lastStockCtrl;
    @XmlElement(name = "AirV", required = true)
    protected String airV;
    @XmlElement(name = "FirstTkNum", required = true)
    protected String firstTkNum;
    @XmlElement(name = "LastTkNum", required = true)
    protected String lastTkNum;
    @XmlElement(name = "ItinInvNum", required = true)
    protected String itinInvNum;
    @XmlElement(name = "Crncy")
    protected String crncy;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "Fare", required = true)
    protected String fare;
    @XmlElement(name = "TkType", required = true)
    protected String tkType;
    @XmlElement(name = "Dt", required = true)
    protected String dt;
    @XmlElement(name = "Tm", required = true)
    protected String tm;
    @XmlElement(name = "VndIssueDt")
    protected String vndIssueDt;
    @XmlElement(name = "CurHistoryInd")
    protected String curHistoryInd;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the firstStockCtrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstStockCtrl() {
        return firstStockCtrl;
    }

    /**
     * Sets the value of the firstStockCtrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstStockCtrl(String value) {
        this.firstStockCtrl = value;
    }

    /**
     * Gets the value of the lastStockCtrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastStockCtrl() {
        return lastStockCtrl;
    }

    /**
     * Sets the value of the lastStockCtrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastStockCtrl(String value) {
        this.lastStockCtrl = value;
    }

    /**
     * Gets the value of the airV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirV() {
        return airV;
    }

    /**
     * Sets the value of the airV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirV(String value) {
        this.airV = value;
    }

    /**
     * Gets the value of the firstTkNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstTkNum() {
        return firstTkNum;
    }

    /**
     * Sets the value of the firstTkNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstTkNum(String value) {
        this.firstTkNum = value;
    }

    /**
     * Gets the value of the lastTkNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTkNum() {
        return lastTkNum;
    }

    /**
     * Sets the value of the lastTkNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTkNum(String value) {
        this.lastTkNum = value;
    }

    /**
     * Gets the value of the itinInvNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItinInvNum() {
        return itinInvNum;
    }

    /**
     * Sets the value of the itinInvNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItinInvNum(String value) {
        this.itinInvNum = value;
    }

    /**
     * Gets the value of the crncy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrncy() {
        return crncy;
    }

    /**
     * Sets the value of the crncy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrncy(String value) {
        this.crncy = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the fare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFare() {
        return fare;
    }

    /**
     * Sets the value of the fare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFare(String value) {
        this.fare = value;
    }

    /**
     * Gets the value of the tkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTkType() {
        return tkType;
    }

    /**
     * Sets the value of the tkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTkType(String value) {
        this.tkType = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDt(String value) {
        this.dt = value;
    }

    /**
     * Gets the value of the tm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTm() {
        return tm;
    }

    /**
     * Sets the value of the tm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTm(String value) {
        this.tm = value;
    }

    /**
     * Gets the value of the vndIssueDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVndIssueDt() {
        return vndIssueDt;
    }

    /**
     * Sets the value of the vndIssueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVndIssueDt(String value) {
        this.vndIssueDt = value;
    }

    /**
     * Gets the value of the curHistoryInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurHistoryInd() {
        return curHistoryInd;
    }

    /**
     * Sets the value of the curHistoryInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurHistoryInd(String value) {
        this.curHistoryInd = value;
    }

}
