//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DisplayAction" minOccurs="0"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareNumInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "displayAction",
    "fareNumInfo"
})
@XmlRootElement(name = "FareRedisplayMods")
public class FareRedisplayMods implements Serializable
{

    @XmlElement(name = "DisplayAction")
    protected DisplayAction displayAction;
    @XmlElement(name = "FareNumInfo")
    protected FareNumInfo fareNumInfo;

    /**
     * Gets the value of the displayAction property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayAction }
     *     
     */
    public DisplayAction getDisplayAction() {
        return displayAction;
    }

    /**
     * Sets the value of the displayAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayAction }
     *     
     */
    public void setDisplayAction(DisplayAction value) {
        this.displayAction = value;
    }

    /**
     * Gets the value of the fareNumInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FareNumInfo }
     *     
     */
    public FareNumInfo getFareNumInfo() {
        return fareNumInfo;
    }

    /**
     * Sets the value of the fareNumInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FareNumInfo }
     *     
     */
    public void setFareNumInfo(FareNumInfo value) {
        this.fareNumInfo = value;
    }

}
