//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PsgrDescNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ODNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FIC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psgrDescNum",
    "odNum",
    "fic"
})
@XmlRootElement(name = "FICInfo")
public class FICInfo
    implements Serializable
{

    @XmlElement(name = "PsgrDescNum", required = true)
    protected String psgrDescNum;
    @XmlElement(name = "ODNum", required = true)
    protected String odNum;
    @XmlElement(name = "FIC", required = true)
    protected String fic;

    /**
     * Gets the value of the psgrDescNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsgrDescNum() {
        return psgrDescNum;
    }

    /**
     * Sets the value of the psgrDescNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsgrDescNum(String value) {
        this.psgrDescNum = value;
    }

    /**
     * Gets the value of the odNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODNum() {
        return odNum;
    }

    /**
     * Sets the value of the odNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODNum(String value) {
        this.odNum = value;
    }

    /**
     * Gets the value of the fic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIC() {
        return fic;
    }

    /**
     * Sets the value of the fic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIC(String value) {
        this.fic = value;
    }

}
