//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TypeROXQual"/>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ID"/>
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Contents"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeROXQual",
    "id",
    "contents"
})
@XmlRootElement(name = "Fld")
public class Fld
    implements Serializable
{

    @XmlElement(name = "TypeROXQual")
    protected TypeROXQual typeROXQual;
    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "Contents")
    protected String contents;

    /**
     * Gets the value of the typeROXQual property.
     * 
     * @return
     *     possible object is
     *     {@link TypeROXQual }
     *     
     */
    public TypeROXQual getTypeROXQual() {
        return typeROXQual;
    }

    /**
     * Sets the value of the typeROXQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeROXQual }
     *     
     */
    public void setTypeROXQual(TypeROXQual value) {
        this.typeROXQual = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContents(String value) {
        this.contents = value;
    }

}
