//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}GenRmkNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CreationDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CreationTm"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}GenlRmkQual"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}GenRmk"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genRmkNum",
    "creationDt",
    "creationTm",
    "genlRmkQual",
    "genRmk"
})
@XmlRootElement(name = "GenRmkInfo")
public class GenRmkInfo implements Serializable
{

    @XmlElement(name = "GenRmkNum", required = true)
    protected String genRmkNum;
    @XmlElement(name = "CreationDt", required = true)
    protected String creationDt;
    @XmlElement(name = "CreationTm", required = true)
    protected String creationTm;
    @XmlElement(name = "GenlRmkQual", required = true)
    protected String genlRmkQual;
    @XmlElement(name = "GenRmk", required = true)
    protected String genRmk;

    /**
     * Gets the value of the genRmkNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenRmkNum() {
        return genRmkNum;
    }

    /**
     * Sets the value of the genRmkNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenRmkNum(String value) {
        this.genRmkNum = value;
    }

    /**
     * Gets the value of the creationDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDt() {
        return creationDt;
    }

    /**
     * Sets the value of the creationDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDt(String value) {
        this.creationDt = value;
    }

    /**
     * Gets the value of the creationTm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTm() {
        return creationTm;
    }

    /**
     * Sets the value of the creationTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTm(String value) {
        this.creationTm = value;
    }

    /**
     * Gets the value of the genlRmkQual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenlRmkQual() {
        return genlRmkQual;
    }

    /**
     * Sets the value of the genlRmkQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenlRmkQual(String value) {
        this.genlRmkQual = value;
    }

    /**
     * Gets the value of the genRmk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenRmk() {
        return genRmk;
    }

    /**
     * Sets the value of the genRmk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenRmk(String value) {
        this.genRmk = value;
    }

}
