//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CRS"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PCC"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QCat"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DtRange"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "crs",
    "pcc",
    "qNum",
    "qCat",
    "dtRange"
})
@XmlRootElement(name = "GlobAccessCRS")
public class GlobAccessCRS
    implements Serializable
{

    @XmlElement(name = "CRS", required = true)
    protected String crs;
    @XmlElement(name = "PCC", required = true)
    protected String pcc;
    @XmlElement(name = "QNum", required = true)
    protected String qNum;
    @XmlElement(name = "QCat", required = true)
    protected String qCat;
    @XmlElement(name = "DtRange", required = true)
    protected String dtRange;

    /**
     * Gets the value of the crs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRS() {
        return crs;
    }

    /**
     * Sets the value of the crs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRS(String value) {
        this.crs = value;
    }

    /**
     * Gets the value of the pcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCC() {
        return pcc;
    }

    /**
     * Sets the value of the pcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCC(String value) {
        this.pcc = value;
    }

    /**
     * Gets the value of the qNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQNum() {
        return qNum;
    }

    /**
     * Sets the value of the qNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQNum(String value) {
        this.qNum = value;
    }

    /**
     * Gets the value of the qCat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQCat() {
        return qCat;
    }

    /**
     * Sets the value of the qCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQCat(String value) {
        this.qCat = value;
    }

    /**
     * Gets the value of the dtRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtRange() {
        return dtRange;
    }

    /**
     * Sets the value of the dtRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtRange(String value) {
        this.dtRange = value;
    }

}
