//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PrimarySDNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SecondarySDNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ChgInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primarySDNum",
    "secondarySDNum",
    "chgInd",
    "text"
})
@XmlRootElement(name = "IMU")
public class IMU
    implements Serializable
{

    @XmlElement(name = "PrimarySDNum", required = true)
    protected String primarySDNum;
    @XmlElement(name = "SecondarySDNum", required = true)
    protected String secondarySDNum;
    @XmlElement(name = "ChgInd", required = true)
    protected String chgInd;
    @XmlElement(name = "Text", required = true)
    protected String text;

    /**
     * Gets the value of the primarySDNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimarySDNum() {
        return primarySDNum;
    }

    /**
     * Sets the value of the primarySDNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarySDNum(String value) {
        this.primarySDNum = value;
    }

    /**
     * Gets the value of the secondarySDNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondarySDNum() {
        return secondarySDNum;
    }

    /**
     * Sets the value of the secondarySDNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondarySDNum(String value) {
        this.secondarySDNum = value;
    }

    /**
     * Gets the value of the chgInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChgInd() {
        return chgInd;
    }

    /**
     * Sets the value of the chgInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChgInd(String value) {
        this.chgInd = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
