//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}UniqueKey"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QuoteNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareComponentNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PriceUnitNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare1"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare2"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare3"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}HoursMax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DaysMax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}MonthsMax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}OccurIndMax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SameDayMax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}StartIndMax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CompletionInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare4"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare5"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare6"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare7"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare8"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spare9"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TmDOWMin"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NumOccurMin"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueKey",
    "quoteNum",
    "fareComponentNum",
    "priceUnitNum",
    "spare1",
    "spare2",
    "spare3",
    "hoursMax",
    "daysMax",
    "monthsMax",
    "occurIndMax",
    "sameDayMax",
    "startIndMax",
    "completionInd",
    "spare4",
    "spare5",
    "spare6",
    "spare7",
    "spare8",
    "spare9",
    "tmDOWMin",
    "numOccurMin"
})
@XmlRootElement(name = "MaxStayRules")
public class MaxStayRules
    implements Serializable
{

    @XmlElement(name = "UniqueKey", required = true)
    protected String uniqueKey;
    @XmlElement(name = "QuoteNum", required = true)
    protected String quoteNum;
    @XmlElement(name = "FareComponentNum", required = true)
    protected String fareComponentNum;
    @XmlElement(name = "PriceUnitNum", required = true)
    protected String priceUnitNum;
    @XmlElement(name = "Spare1", required = true)
    protected String spare1;
    @XmlElement(name = "Spare2", required = true)
    protected String spare2;
    @XmlElement(name = "Spare3", required = true)
    protected String spare3;
    @XmlElement(name = "HoursMax", required = true)
    protected String hoursMax;
    @XmlElement(name = "DaysMax", required = true)
    protected String daysMax;
    @XmlElement(name = "MonthsMax", required = true)
    protected String monthsMax;
    @XmlElement(name = "OccurIndMax", required = true)
    protected String occurIndMax;
    @XmlElement(name = "SameDayMax", required = true)
    protected String sameDayMax;
    @XmlElement(name = "StartIndMax", required = true)
    protected String startIndMax;
    @XmlElement(name = "CompletionInd", required = true)
    protected String completionInd;
    @XmlElement(name = "Spare4", required = true)
    protected String spare4;
    @XmlElement(name = "Spare5", required = true)
    protected String spare5;
    @XmlElement(name = "Spare6", required = true)
    protected String spare6;
    @XmlElement(name = "Spare7", required = true)
    protected String spare7;
    @XmlElement(name = "Spare8", required = true)
    protected String spare8;
    @XmlElement(name = "Spare9", required = true)
    protected String spare9;
    @XmlElement(name = "TmDOWMin", required = true)
    protected String tmDOWMin;
    @XmlElement(name = "NumOccurMin", required = true)
    protected String numOccurMin;

    /**
     * Gets the value of the uniqueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKey() {
        return uniqueKey;
    }

    /**
     * Sets the value of the uniqueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKey(String value) {
        this.uniqueKey = value;
    }

    /**
     * Gets the value of the quoteNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteNum() {
        return quoteNum;
    }

    /**
     * Sets the value of the quoteNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteNum(String value) {
        this.quoteNum = value;
    }

    /**
     * Gets the value of the fareComponentNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareComponentNum() {
        return fareComponentNum;
    }

    /**
     * Sets the value of the fareComponentNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareComponentNum(String value) {
        this.fareComponentNum = value;
    }

    /**
     * Gets the value of the priceUnitNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceUnitNum() {
        return priceUnitNum;
    }

    /**
     * Sets the value of the priceUnitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceUnitNum(String value) {
        this.priceUnitNum = value;
    }

    /**
     * Gets the value of the spare1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * Sets the value of the spare1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare1(String value) {
        this.spare1 = value;
    }

    /**
     * Gets the value of the spare2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * Sets the value of the spare2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare2(String value) {
        this.spare2 = value;
    }

    /**
     * Gets the value of the spare3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * Sets the value of the spare3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare3(String value) {
        this.spare3 = value;
    }

    /**
     * Gets the value of the hoursMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursMax() {
        return hoursMax;
    }

    /**
     * Sets the value of the hoursMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursMax(String value) {
        this.hoursMax = value;
    }

    /**
     * Gets the value of the daysMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysMax() {
        return daysMax;
    }

    /**
     * Sets the value of the daysMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysMax(String value) {
        this.daysMax = value;
    }

    /**
     * Gets the value of the monthsMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthsMax() {
        return monthsMax;
    }

    /**
     * Sets the value of the monthsMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthsMax(String value) {
        this.monthsMax = value;
    }

    /**
     * Gets the value of the occurIndMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccurIndMax() {
        return occurIndMax;
    }

    /**
     * Sets the value of the occurIndMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccurIndMax(String value) {
        this.occurIndMax = value;
    }

    /**
     * Gets the value of the sameDayMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSameDayMax() {
        return sameDayMax;
    }

    /**
     * Sets the value of the sameDayMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSameDayMax(String value) {
        this.sameDayMax = value;
    }

    /**
     * Gets the value of the startIndMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartIndMax() {
        return startIndMax;
    }

    /**
     * Sets the value of the startIndMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartIndMax(String value) {
        this.startIndMax = value;
    }

    /**
     * Gets the value of the completionInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionInd() {
        return completionInd;
    }

    /**
     * Sets the value of the completionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionInd(String value) {
        this.completionInd = value;
    }

    /**
     * Gets the value of the spare4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare4() {
        return spare4;
    }

    /**
     * Sets the value of the spare4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare4(String value) {
        this.spare4 = value;
    }

    /**
     * Gets the value of the spare5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare5() {
        return spare5;
    }

    /**
     * Sets the value of the spare5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare5(String value) {
        this.spare5 = value;
    }

    /**
     * Gets the value of the spare6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare6() {
        return spare6;
    }

    /**
     * Sets the value of the spare6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare6(String value) {
        this.spare6 = value;
    }

    /**
     * Gets the value of the spare7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare7() {
        return spare7;
    }

    /**
     * Sets the value of the spare7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare7(String value) {
        this.spare7 = value;
    }

    /**
     * Gets the value of the spare8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare8() {
        return spare8;
    }

    /**
     * Sets the value of the spare8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare8(String value) {
        this.spare8 = value;
    }

    /**
     * Gets the value of the spare9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpare9() {
        return spare9;
    }

    /**
     * Sets the value of the spare9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpare9(String value) {
        this.spare9 = value;
    }

    /**
     * Gets the value of the tmDOWMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmDOWMin() {
        return tmDOWMin;
    }

    /**
     * Sets the value of the tmDOWMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmDOWMin(String value) {
        this.tmDOWMin = value;
    }

    /**
     * Gets the value of the numOccurMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOccurMin() {
        return numOccurMin;
    }

    /**
     * Sets the value of the numOccurMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOccurMin(String value) {
        this.numOccurMin = value;
    }

}
