//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PsgrName"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TourOperator"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Location"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ValidFor"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}RelatedTktNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Commission"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}MCOTax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TaxCode"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}MCOAmt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Currency"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EquivFarePaid"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EquivCurrency"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BankSellRate"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PlatingCarrier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psgrName",
    "tourOperator",
    "location",
    "validFor",
    "relatedTktNum",
    "commission",
    "mcoTax",
    "taxCode",
    "mcoAmt",
    "currency",
    "equivFarePaid",
    "equivCurrency",
    "bankSellRate",
    "platingCarrier"
})
@XmlRootElement(name = "MCOMainData")
public class MCOMainData implements Serializable
{

    @XmlElement(name = "PsgrName", required = true)
    protected String psgrName;
    @XmlElement(name = "TourOperator", required = true)
    protected String tourOperator;
    @XmlElement(name = "Location", required = true)
    protected String location;
    @XmlElement(name = "ValidFor", required = true)
    protected String validFor;
    @XmlElement(name = "RelatedTktNum", required = true)
    protected String relatedTktNum;
    @XmlElement(name = "Commission", required = true)
    protected Commission commission;
    @XmlElement(name = "MCOTax", required = true)
    protected String mcoTax;
    @XmlElement(name = "TaxCode", required = true)
    protected String taxCode;
    @XmlElement(name = "MCOAmt", required = true)
    protected String mcoAmt;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "EquivFarePaid", required = true)
    protected String equivFarePaid;
    @XmlElement(name = "EquivCurrency", required = true)
    protected String equivCurrency;
    @XmlElement(name = "BankSellRate", required = true)
    protected String bankSellRate;
    @XmlElement(name = "PlatingCarrier", required = true)
    protected String platingCarrier;

    /**
     * Gets the value of the psgrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsgrName() {
        return psgrName;
    }

    /**
     * Sets the value of the psgrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsgrName(String value) {
        this.psgrName = value;
    }

    /**
     * Gets the value of the tourOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTourOperator() {
        return tourOperator;
    }

    /**
     * Sets the value of the tourOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTourOperator(String value) {
        this.tourOperator = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the validFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidFor() {
        return validFor;
    }

    /**
     * Sets the value of the validFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidFor(String value) {
        this.validFor = value;
    }

    /**
     * Gets the value of the relatedTktNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedTktNum() {
        return relatedTktNum;
    }

    /**
     * Sets the value of the relatedTktNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedTktNum(String value) {
        this.relatedTktNum = value;
    }

    /**
     * Gets the value of the commission property.
     * 
     * @return
     *     possible object is
     *     {@link Commission }
     *     
     */
    public Commission getCommission() {
        return commission;
    }

    /**
     * Sets the value of the commission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commission }
     *     
     */
    public void setCommission(Commission value) {
        this.commission = value;
    }

    /**
     * Gets the value of the mcoTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCOTax() {
        return mcoTax;
    }

    /**
     * Sets the value of the mcoTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCOTax(String value) {
        this.mcoTax = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCode(String value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the mcoAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCOAmt() {
        return mcoAmt;
    }

    /**
     * Sets the value of the mcoAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCOAmt(String value) {
        this.mcoAmt = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the equivFarePaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquivFarePaid() {
        return equivFarePaid;
    }

    /**
     * Sets the value of the equivFarePaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquivFarePaid(String value) {
        this.equivFarePaid = value;
    }

    /**
     * Gets the value of the equivCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquivCurrency() {
        return equivCurrency;
    }

    /**
     * Sets the value of the equivCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquivCurrency(String value) {
        this.equivCurrency = value;
    }

    /**
     * Gets the value of the bankSellRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankSellRate() {
        return bankSellRate;
    }

    /**
     * Sets the value of the bankSellRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankSellRate(String value) {
        this.bankSellRate = value;
    }

    /**
     * Gets the value of the platingCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatingCarrier() {
        return platingCarrier;
    }

    /**
     * Sets the value of the platingCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatingCarrier(String value) {
        this.platingCarrier = value;
    }

}
