//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Rmk"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AdditionalRmkAry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rmk",
    "additionalRmkAry"
})
@XmlRootElement(name = "MCORemarks")
public class MCORemarks implements Serializable
{

    @XmlElement(name = "Rmk", required = true)
    protected String rmk;
    @XmlElement(name = "AdditionalRmkAry", required = true)
    protected AdditionalRmkAry additionalRmkAry;

    /**
     * Gets the value of the rmk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * Sets the value of the rmk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmk(String value) {
        this.rmk = value;
    }

    /**
     * Gets the value of the additionalRmkAry property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalRmkAry }
     *     
     */
    public AdditionalRmkAry getAdditionalRmkAry() {
        return additionalRmkAry;
    }

    /**
     * Sets the value of the additionalRmkAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalRmkAry }
     *     
     */
    public void setAdditionalRmkAry(AdditionalRmkAry value) {
        this.additionalRmkAry = value;
    }

}
