//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}UniqueKey"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QuoteNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareComponentNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PriceUnitNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DepRequiredAry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueKey",
    "quoteNum",
    "fareComponentNum",
    "priceUnitNum",
    "depRequiredAry"
})
@XmlRootElement(name = "PenaltyRules")
public class PenaltyRules
    implements Serializable
{

    @XmlElement(name = "UniqueKey", required = true)
    protected String uniqueKey;
    @XmlElement(name = "QuoteNum", required = true)
    protected String quoteNum;
    @XmlElement(name = "FareComponentNum", required = true)
    protected String fareComponentNum;
    @XmlElement(name = "PriceUnitNum", required = true)
    protected String priceUnitNum;
    @XmlElement(name = "DepRequiredAry", required = true)
    protected DepRequiredAry depRequiredAry;

    /**
     * Gets the value of the uniqueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKey() {
        return uniqueKey;
    }

    /**
     * Sets the value of the uniqueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKey(String value) {
        this.uniqueKey = value;
    }

    /**
     * Gets the value of the quoteNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteNum() {
        return quoteNum;
    }

    /**
     * Sets the value of the quoteNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteNum(String value) {
        this.quoteNum = value;
    }

    /**
     * Gets the value of the fareComponentNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareComponentNum() {
        return fareComponentNum;
    }

    /**
     * Sets the value of the fareComponentNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareComponentNum(String value) {
        this.fareComponentNum = value;
    }

    /**
     * Gets the value of the priceUnitNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceUnitNum() {
        return priceUnitNum;
    }

    /**
     * Sets the value of the priceUnitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceUnitNum(String value) {
        this.priceUnitNum = value;
    }

    /**
     * Gets the value of the depRequiredAry property.
     * 
     * @return
     *     possible object is
     *     {@link DepRequiredAry }
     *     
     */
    public DepRequiredAry getDepRequiredAry() {
        return depRequiredAry;
    }

    /**
     * Sets the value of the depRequiredAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepRequiredAry }
     *     
     */
    public void setDepRequiredAry(DepRequiredAry value) {
        this.depRequiredAry = value;
    }

}
