//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SeatPref"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SmokePref"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DefFOPAir"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DefFOPCar"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DefFOPHotel"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}HtlSpclInfo"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CarSpclInfo"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SSRCodeAry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seatPref",
    "smokePref",
    "defFOPAir",
    "defFOPCar",
    "defFOPHotel",
    "htlSpclInfo",
    "carSpclInfo",
    "ssrCodeAry"
})
@XmlRootElement(name = "PersonalInfoUpdate")
public class PersonalInfoUpdate
    implements Serializable
{

    @XmlElement(name = "SeatPref", required = true)
    protected String seatPref;
    @XmlElement(name = "SmokePref", required = true)
    protected String smokePref;
    @XmlElement(name = "DefFOPAir", required = true)
    protected String defFOPAir;
    @XmlElement(name = "DefFOPCar", required = true)
    protected String defFOPCar;
    @XmlElement(name = "DefFOPHotel", required = true)
    protected String defFOPHotel;
    @XmlElement(name = "HtlSpclInfo", required = true)
    protected String htlSpclInfo;
    @XmlElement(name = "CarSpclInfo", required = true)
    protected String carSpclInfo;
    @XmlElement(name = "SSRCodeAry", required = true)
    protected SSRCodeAry ssrCodeAry;

    /**
     * Gets the value of the seatPref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatPref() {
        return seatPref;
    }

    /**
     * Sets the value of the seatPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatPref(String value) {
        this.seatPref = value;
    }

    /**
     * Gets the value of the smokePref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmokePref() {
        return smokePref;
    }

    /**
     * Sets the value of the smokePref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmokePref(String value) {
        this.smokePref = value;
    }

    /**
     * Gets the value of the defFOPAir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefFOPAir() {
        return defFOPAir;
    }

    /**
     * Sets the value of the defFOPAir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefFOPAir(String value) {
        this.defFOPAir = value;
    }

    /**
     * Gets the value of the defFOPCar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefFOPCar() {
        return defFOPCar;
    }

    /**
     * Sets the value of the defFOPCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefFOPCar(String value) {
        this.defFOPCar = value;
    }

    /**
     * Gets the value of the defFOPHotel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefFOPHotel() {
        return defFOPHotel;
    }

    /**
     * Sets the value of the defFOPHotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefFOPHotel(String value) {
        this.defFOPHotel = value;
    }

    /**
     * Gets the value of the htlSpclInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtlSpclInfo() {
        return htlSpclInfo;
    }

    /**
     * Sets the value of the htlSpclInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtlSpclInfo(String value) {
        this.htlSpclInfo = value;
    }

    /**
     * Gets the value of the carSpclInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarSpclInfo() {
        return carSpclInfo;
    }

    /**
     * Sets the value of the carSpclInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarSpclInfo(String value) {
        this.carSpclInfo = value;
    }

    /**
     * Gets the value of the ssrCodeAry property.
     * 
     * @return
     *     possible object is
     *     {@link SSRCodeAry }
     *     
     */
    public SSRCodeAry getSSRCodeAry() {
        return ssrCodeAry;
    }

    /**
     * Sets the value of the ssrCodeAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSRCodeAry }
     *     
     */
    public void setSSRCodeAry(SSRCodeAry value) {
        this.ssrCodeAry = value;
    }

}
