//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PNRBFManagement_10"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DocProdFareManipulation_7"/>
 *         &lt;element name="TerminalCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand"
})
@XmlRootElement(name = "PNRBFManagement_10List")
public class PNRBFManagement10List
    implements Serializable
{

    @XmlElements({
        @XmlElement(name = "PNRBFManagement_10", type = PNRBFManagement10 .class),
        @XmlElement(name = "TerminalCommand", type = String.class),
        @XmlElement(name = "DocProdFareManipulation_7", type = DocProdFareManipulation7 .class)
    })
    protected List<Object> pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand;

    /**
     * Gets the value of the pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPNRBFManagement10OrDocProdFareManipulation7OrTerminalCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PNRBFManagement10 }
     * {@link String }
     * {@link DocProdFareManipulation7 }
     * 
     * 
     */
    public List<Object> getPNRBFManagement10OrDocProdFareManipulation7OrTerminalCommand() {
        if (pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand == null) {
            pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand = new ArrayList<Object>();
        }
        return this.pnrbfManagement10OrDocProdFareManipulation7OrTerminalCommand;
    }

}
