//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}GFAXNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SSRCode"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SegNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AppliesToAry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gfaxNum",
    "ssrCode",
    "status",
    "segNum",
    "appliesToAry"
})
@XmlRootElement(name = "ProgramaticSSR")
public class ProgramaticSSR implements Serializable
{

    @XmlElement(name = "GFAXNum", required = true)
    protected String gfaxNum;
    @XmlElement(name = "SSRCode", required = true)
    protected String ssrCode;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "SegNum", required = true)
    protected String segNum;
    @XmlElement(name = "AppliesToAry", required = true)
    protected AppliesToType appliesToAry;

    /**
     * Gets the value of the gfaxNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGFAXNum() {
        return gfaxNum;
    }

    /**
     * Sets the value of the gfaxNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGFAXNum(String value) {
        this.gfaxNum = value;
    }

    /**
     * Gets the value of the ssrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSRCode() {
        return ssrCode;
    }

    /**
     * Sets the value of the ssrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSRCode(String value) {
        this.ssrCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the segNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegNum() {
        return segNum;
    }

    /**
     * Sets the value of the segNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegNum(String value) {
        this.segNum = value;
    }

    /**
     * Gets the value of the appliesToAry property.
     * 
     * @return
     *     possible object is
     *     {@link AppliesToType }
     *     
     */
    public AppliesToType getAppliesToAry() {
        return appliesToAry;
    }

    /**
     * Sets the value of the appliesToAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppliesToType }
     *     
     */
    public void setAppliesToAry(AppliesToType value) {
        this.appliesToAry = value;
    }

}
