//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}LNameNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PsgrNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AbsNameNum"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PIC"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PTC"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Age"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PricePTCOnly"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DiscOrIncrInd"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AmtOrPercent"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PersonalGeoType"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PersonalGeoData"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TIC" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TkDesignator"/>
 *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TkCode"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lNameNum",
    "psgrNum",
    "absNameNum",
    "pic",
    "ptc",
    "age",
    "pricePTCOnly",
    "discOrIncrInd",
    "amtOrPercent",
    "personalGeoType",
    "personalGeoData",
    "tic",
    "tkDesignator",
    "tkCode"
})
@XmlRootElement(name = "Psgr")
public class Psgr
    implements Serializable
{

    @XmlElement(name = "LNameNum", required = true)
    protected String lNameNum;
    @XmlElement(name = "PsgrNum", required = true)
    protected String psgrNum;
    @XmlElement(name = "AbsNameNum", required = true)
    protected String absNameNum;
    @XmlElement(name = "PIC")
    protected String pic;
    @XmlElement(name = "PTC")
    protected String ptc;
    @XmlElement(name = "Age")
    protected String age;
    @XmlElement(name = "PricePTCOnly")
    protected String pricePTCOnly;
    @XmlElement(name = "DiscOrIncrInd")
    protected String discOrIncrInd;
    @XmlElement(name = "AmtOrPercent")
    protected String amtOrPercent;
    @XmlElement(name = "PersonalGeoType")
    protected String personalGeoType;
    @XmlElement(name = "PersonalGeoData")
    protected String personalGeoData;
    @XmlElement(name = "TIC")
    protected String tic;
    @XmlElement(name = "TkDesignator")
    protected String tkDesignator;
    @XmlElement(name = "TkCode")
    protected String tkCode;

    /**
     * Gets the value of the lNameNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLNameNum() {
        return lNameNum;
    }

    /**
     * Sets the value of the lNameNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLNameNum(String value) {
        this.lNameNum = value;
    }

    /**
     * Gets the value of the psgrNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsgrNum() {
        return psgrNum;
    }

    /**
     * Sets the value of the psgrNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsgrNum(String value) {
        this.psgrNum = value;
    }

    /**
     * Gets the value of the absNameNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsNameNum() {
        return absNameNum;
    }

    /**
     * Sets the value of the absNameNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsNameNum(String value) {
        this.absNameNum = value;
    }

    /**
     * Gets the value of the pic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIC() {
        return pic;
    }

    /**
     * Sets the value of the pic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIC(String value) {
        this.pic = value;
    }

    /**
     * Gets the value of the ptc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPTC() {
        return ptc;
    }

    /**
     * Sets the value of the ptc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPTC(String value) {
        this.ptc = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the pricePTCOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricePTCOnly() {
        return pricePTCOnly;
    }

    /**
     * Sets the value of the pricePTCOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricePTCOnly(String value) {
        this.pricePTCOnly = value;
    }

    /**
     * Gets the value of the discOrIncrInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscOrIncrInd() {
        return discOrIncrInd;
    }

    /**
     * Sets the value of the discOrIncrInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscOrIncrInd(String value) {
        this.discOrIncrInd = value;
    }

    /**
     * Gets the value of the amtOrPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmtOrPercent() {
        return amtOrPercent;
    }

    /**
     * Sets the value of the amtOrPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmtOrPercent(String value) {
        this.amtOrPercent = value;
    }

    /**
     * Gets the value of the personalGeoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalGeoType() {
        return personalGeoType;
    }

    /**
     * Sets the value of the personalGeoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalGeoType(String value) {
        this.personalGeoType = value;
    }

    /**
     * Gets the value of the personalGeoData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalGeoData() {
        return personalGeoData;
    }

    /**
     * Sets the value of the personalGeoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalGeoData(String value) {
        this.personalGeoData = value;
    }

    /**
     * Gets the value of the tic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIC() {
        return tic;
    }

    /**
     * Sets the value of the tic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIC(String value) {
        this.tic = value;
    }

    /**
     * Gets the value of the tkDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTkDesignator() {
        return tkDesignator;
    }

    /**
     * Sets the value of the tkDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTkDesignator(String value) {
        this.tkDesignator = value;
    }

    /**
     * Gets the value of the tkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTkCode() {
        return tkCode;
    }

    /**
     * Sets the value of the tkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTkCode(String value) {
        this.tkCode = value;
    }

}
