//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FeeAppliesToInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FeeTypeInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FeeValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "feeAppliesToInd",
    "feeTypeInd",
    "feeValue"
})
@XmlRootElement(name = "PTATODFee")
public class PTATODFee implements Serializable
{

    @XmlElement(name = "FeeAppliesToInd", required = true)
    protected String feeAppliesToInd;
    @XmlElement(name = "FeeTypeInd", required = true)
    protected String feeTypeInd;
    @XmlElement(name = "FeeValue", required = true)
    protected String feeValue;

    /**
     * Gets the value of the feeAppliesToInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeAppliesToInd() {
        return feeAppliesToInd;
    }

    /**
     * Sets the value of the feeAppliesToInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeAppliesToInd(String value) {
        this.feeAppliesToInd = value;
    }

    /**
     * Gets the value of the feeTypeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeTypeInd() {
        return feeTypeInd;
    }

    /**
     * Sets the value of the feeTypeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeTypeInd(String value) {
        this.feeTypeInd = value;
    }

    /**
     * Gets the value of the feeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeValue() {
        return feeValue;
    }

    /**
     * Sets the value of the feeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeValue(String value) {
        this.feeValue = value;
    }

}
