//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}StartSeg"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EndSeg"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BICOverride"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}StopoverConx"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BreakInd"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareType"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FIC"/>
 *             &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PFQual"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startSeg",
    "endSeg",
    "bicOverride",
    "stopoverConx",
    "breakInd",
    "fareType",
    "fic",
    "pfQual"
})
@XmlRootElement(name = "SegRange")
public class SegRange
    implements Serializable
{

    @XmlElement(name = "StartSeg", required = true)
    protected String startSeg;
    @XmlElement(name = "EndSeg", required = true)
    protected String endSeg;
    @XmlElement(name = "BICOverride")
    protected String bicOverride;
    @XmlElement(name = "StopoverConx")
    protected String stopoverConx;
    @XmlElement(name = "BreakInd")
    protected String breakInd;
    @XmlElement(name = "FareType")
    protected String fareType;
    @XmlElement(name = "FIC")
    protected String fic;
    @XmlElement(name = "PFQual")
    protected PFQual pfQual;

    /**
     * Gets the value of the startSeg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartSeg() {
        return startSeg;
    }

    /**
     * Sets the value of the startSeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartSeg(String value) {
        this.startSeg = value;
    }

    /**
     * Gets the value of the endSeg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndSeg() {
        return endSeg;
    }

    /**
     * Sets the value of the endSeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndSeg(String value) {
        this.endSeg = value;
    }

    /**
     * Gets the value of the bicOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBICOverride() {
        return bicOverride;
    }

    /**
     * Sets the value of the bicOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBICOverride(String value) {
        this.bicOverride = value;
    }

    /**
     * Gets the value of the stopoverConx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopoverConx() {
        return stopoverConx;
    }

    /**
     * Sets the value of the stopoverConx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopoverConx(String value) {
        this.stopoverConx = value;
    }

    /**
     * Gets the value of the breakInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakInd() {
        return breakInd;
    }

    /**
     * Sets the value of the breakInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakInd(String value) {
        this.breakInd = value;
    }

    /**
     * Gets the value of the fareType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareType() {
        return fareType;
    }

    /**
     * Sets the value of the fareType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareType(String value) {
        this.fareType = value;
    }

    /**
     * Gets the value of the fic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIC() {
        return fic;
    }

    /**
     * Sets the value of the fic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIC(String value) {
        this.fic = value;
    }

    /**
     * Gets the value of the pfQual property.
     * 
     * @return
     *     possible object is
     *     {@link PFQual }
     *     
     */
    public PFQual getPFQual() {
        return pfQual;
    }

    /**
     * Sets the value of the pfQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link PFQual }
     *     
     */
    public void setPFQual(PFQual value) {
        this.pfQual = value;
    }

}
