//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TargetCRS"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BranchInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BranchPCC"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AffiliateName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "targetCRS",
    "branchInd",
    "branchPCC",
    "affiliateName"
})
@XmlRootElement(name = "TargetCRSInfo")
public class TargetCRSInfo implements Serializable
{

    @XmlElement(name = "TargetCRS", required = true)
    protected String targetCRS;
    @XmlElement(name = "BranchInd", required = true)
    protected String branchInd;
    @XmlElement(name = "BranchPCC", required = true)
    protected String branchPCC;
    @XmlElement(name = "AffiliateName", required = true)
    protected String affiliateName;

    /**
     * Gets the value of the targetCRS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetCRS() {
        return targetCRS;
    }

    /**
     * Sets the value of the targetCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetCRS(String value) {
        this.targetCRS = value;
    }

    /**
     * Gets the value of the branchInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchInd() {
        return branchInd;
    }

    /**
     * Sets the value of the branchInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchInd(String value) {
        this.branchInd = value;
    }

    /**
     * Gets the value of the branchPCC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchPCC() {
        return branchPCC;
    }

    /**
     * Sets the value of the branchPCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchPCC(String value) {
        this.branchPCC = value;
    }

    /**
     * Gets the value of the affiliateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliateName() {
        return affiliateName;
    }

    /**
     * Sets the value of the affiliateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliateName(String value) {
        this.affiliateName = value;
    }

}
