//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QTAUDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BranchPCC"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}QPlacementAry"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qtauDt",
    "branchPCC",
    "qPlacementAry",
    "text"
})
@XmlRootElement(name = "TAUTkArrangement")
public class TAUTkArrangement implements Serializable
{

    @XmlElement(name = "QTAUDt", required = true)
    protected String qtauDt;
    @XmlElement(name = "BranchPCC", required = true)
    protected String branchPCC;
    @XmlElement(name = "QPlacementAry", required = true)
    protected QPlacementAry qPlacementAry;
    @XmlElement(name = "Text")
    protected String text;

    /**
     * Gets the value of the qtauDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTAUDt() {
        return qtauDt;
    }

    /**
     * Sets the value of the qtauDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTAUDt(String value) {
        this.qtauDt = value;
    }

    /**
     * Gets the value of the branchPCC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchPCC() {
        return branchPCC;
    }

    /**
     * Sets the value of the branchPCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchPCC(String value) {
        this.branchPCC = value;
    }

    /**
     * Gets the value of the qPlacementAry property.
     * 
     * @return
     *     possible object is
     *     {@link QPlacementAry }
     *     
     */
    public QPlacementAry getQPlacementAry() {
        return qPlacementAry;
    }

    /**
     * Sets the value of the qPlacementAry property.
     * 
     * @param value
     *     allowed object is
     *     {@link QPlacementAry }
     *     
     */
    public void setQPlacementAry(QPlacementAry value) {
        this.qPlacementAry = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
