//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="TaxData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Country"/>
 *                   &lt;choice>
 *                     &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Amt"/>
 *                     &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TaxAmt"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxData"
})
@XmlRootElement(name = "TaxDataAry")
public class TaxDataAry
    implements Serializable
{

    @XmlElement(name = "TaxData", required = true)
    protected List<TaxDataAry.TaxData> taxData;

    /**
     * Gets the value of the taxData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxDataAry.TaxData }
     * 
     * 
     */
    public List<TaxDataAry.TaxData> getTaxData() {
        if (taxData == null) {
            taxData = new ArrayList<TaxDataAry.TaxData>();
        }
        return this.taxData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Country"/>
     *         &lt;choice>
     *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Amt"/>
     *           &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TaxAmt"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "country",
        "amt",
        "taxAmt"
    })
    public static class TaxData
        implements Serializable
    {

        @XmlElement(name = "Country", required = true)
        protected String country;
        @XmlElement(name = "Amt")
        protected String amt;
        @XmlElement(name = "TaxAmt")
        protected String taxAmt;

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the amt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmt() {
            return amt;
        }

        /**
         * Sets the value of the amt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmt(String value) {
            this.amt = value;
        }

        /**
         * Gets the value of the taxAmt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxAmt() {
            return taxAmt;
        }

        /**
         * Sets the value of the taxAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxAmt(String value) {
            this.taxAmt = value;
        }

    }

}
