//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}UniqueKey"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}RestrictionDateinGMT"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}RestrictionTimeinGMT"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DaysTypeRestriction"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}HoursTypeRestriction"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Spares"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueKey",
    "restrictionDateinGMT",
    "restrictionTimeinGMT",
    "daysTypeRestriction",
    "hoursTypeRestriction",
    "spares"
})
@XmlRootElement(name = "TkRestrictionInfo")
public class TkRestrictionInfo
    implements Serializable
{

    @XmlElement(name = "UniqueKey", required = true)
    protected String uniqueKey;
    @XmlElement(name = "RestrictionDateinGMT", required = true)
    protected String restrictionDateinGMT;
    @XmlElement(name = "RestrictionTimeinGMT", required = true)
    protected String restrictionTimeinGMT;
    @XmlElement(name = "DaysTypeRestriction", required = true)
    protected String daysTypeRestriction;
    @XmlElement(name = "HoursTypeRestriction", required = true)
    protected String hoursTypeRestriction;
    @XmlElement(name = "Spares", required = true)
    protected String spares;

    /**
     * Gets the value of the uniqueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKey() {
        return uniqueKey;
    }

    /**
     * Sets the value of the uniqueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKey(String value) {
        this.uniqueKey = value;
    }

    /**
     * Gets the value of the restrictionDateinGMT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictionDateinGMT() {
        return restrictionDateinGMT;
    }

    /**
     * Sets the value of the restrictionDateinGMT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictionDateinGMT(String value) {
        this.restrictionDateinGMT = value;
    }

    /**
     * Gets the value of the restrictionTimeinGMT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictionTimeinGMT() {
        return restrictionTimeinGMT;
    }

    /**
     * Sets the value of the restrictionTimeinGMT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictionTimeinGMT(String value) {
        this.restrictionTimeinGMT = value;
    }

    /**
     * Gets the value of the daysTypeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysTypeRestriction() {
        return daysTypeRestriction;
    }

    /**
     * Sets the value of the daysTypeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysTypeRestriction(String value) {
        this.daysTypeRestriction = value;
    }

    /**
     * Gets the value of the hoursTypeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursTypeRestriction() {
        return hoursTypeRestriction;
    }

    /**
     * Sets the value of the hoursTypeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursTypeRestriction(String value) {
        this.hoursTypeRestriction = value;
    }

    /**
     * Gets the value of the spares property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpares() {
        return spares;
    }

    /**
     * Sets the value of the spares property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpares(String value) {
        this.spares = value;
    }

}
