//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SegNum"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}StartDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EndDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Vnd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NumPsgrs"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}StartPt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}EndPt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PkgID"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PricingCat"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}ConfNum"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DocMailDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Currency"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BasePrice"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DecPos"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DepDueDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DepAmtDue"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DepRecvDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}OptPrice"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BalanceDueDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BalanceAmt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BalanceRecvDt"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TotTax"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}CancelFee"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}TotAmtDue"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AgncyCommission"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "segNum",
    "status",
    "startDt",
    "endDt",
    "vnd",
    "numPsgrs",
    "startPt",
    "endPt",
    "pkgID",
    "pricingCat",
    "confNum",
    "docMailDt",
    "currency",
    "basePrice",
    "decPos",
    "depDueDt",
    "depAmtDue",
    "depRecvDt",
    "optPrice",
    "balanceDueDt",
    "balanceAmt",
    "balanceRecvDt",
    "totTax",
    "cancelFee",
    "totAmtDue",
    "agncyCommission"
})
@XmlRootElement(name = "TourSeg")
public class TourSeg implements Serializable
{

    @XmlElement(name = "SegNum", required = true)
    protected String segNum;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "StartDt", required = true)
    protected String startDt;
    @XmlElement(name = "EndDt", required = true)
    protected String endDt;
    @XmlElement(name = "Vnd", required = true)
    protected String vnd;
    @XmlElement(name = "NumPsgrs", required = true)
    protected String numPsgrs;
    @XmlElement(name = "StartPt", required = true)
    protected String startPt;
    @XmlElement(name = "EndPt", required = true)
    protected String endPt;
    @XmlElement(name = "PkgID", required = true)
    protected String pkgID;
    @XmlElement(name = "PricingCat", required = true)
    protected String pricingCat;
    @XmlElement(name = "ConfNum", required = true)
    protected String confNum;
    @XmlElement(name = "DocMailDt", required = true)
    protected String docMailDt;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "BasePrice", required = true)
    protected String basePrice;
    @XmlElement(name = "DecPos", required = true)
    protected String decPos;
    @XmlElement(name = "DepDueDt", required = true)
    protected String depDueDt;
    @XmlElement(name = "DepAmtDue", required = true)
    protected String depAmtDue;
    @XmlElement(name = "DepRecvDt", required = true)
    protected String depRecvDt;
    @XmlElement(name = "OptPrice", required = true)
    protected String optPrice;
    @XmlElement(name = "BalanceDueDt", required = true)
    protected String balanceDueDt;
    @XmlElement(name = "BalanceAmt", required = true)
    protected String balanceAmt;
    @XmlElement(name = "BalanceRecvDt", required = true)
    protected String balanceRecvDt;
    @XmlElement(name = "TotTax", required = true)
    protected String totTax;
    @XmlElement(name = "CancelFee", required = true)
    protected String cancelFee;
    @XmlElement(name = "TotAmtDue", required = true)
    protected String totAmtDue;
    @XmlElement(name = "AgncyCommission", required = true)
    protected String agncyCommission;

    /**
     * Gets the value of the segNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegNum() {
        return segNum;
    }

    /**
     * Sets the value of the segNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegNum(String value) {
        this.segNum = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the startDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDt() {
        return startDt;
    }

    /**
     * Sets the value of the startDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDt(String value) {
        this.startDt = value;
    }

    /**
     * Gets the value of the endDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDt() {
        return endDt;
    }

    /**
     * Sets the value of the endDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDt(String value) {
        this.endDt = value;
    }

    /**
     * Gets the value of the vnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnd() {
        return vnd;
    }

    /**
     * Sets the value of the vnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnd(String value) {
        this.vnd = value;
    }

    /**
     * Gets the value of the numPsgrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumPsgrs() {
        return numPsgrs;
    }

    /**
     * Sets the value of the numPsgrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumPsgrs(String value) {
        this.numPsgrs = value;
    }

    /**
     * Gets the value of the startPt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPt() {
        return startPt;
    }

    /**
     * Sets the value of the startPt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPt(String value) {
        this.startPt = value;
    }

    /**
     * Gets the value of the endPt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPt() {
        return endPt;
    }

    /**
     * Sets the value of the endPt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPt(String value) {
        this.endPt = value;
    }

    /**
     * Gets the value of the pkgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkgID() {
        return pkgID;
    }

    /**
     * Sets the value of the pkgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkgID(String value) {
        this.pkgID = value;
    }

    /**
     * Gets the value of the pricingCat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingCat() {
        return pricingCat;
    }

    /**
     * Sets the value of the pricingCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingCat(String value) {
        this.pricingCat = value;
    }

    /**
     * Gets the value of the confNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfNum() {
        return confNum;
    }

    /**
     * Sets the value of the confNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfNum(String value) {
        this.confNum = value;
    }

    /**
     * Gets the value of the docMailDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocMailDt() {
        return docMailDt;
    }

    /**
     * Sets the value of the docMailDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocMailDt(String value) {
        this.docMailDt = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasePrice(String value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the decPos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecPos() {
        return decPos;
    }

    /**
     * Sets the value of the decPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecPos(String value) {
        this.decPos = value;
    }

    /**
     * Gets the value of the depDueDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepDueDt() {
        return depDueDt;
    }

    /**
     * Sets the value of the depDueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepDueDt(String value) {
        this.depDueDt = value;
    }

    /**
     * Gets the value of the depAmtDue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepAmtDue() {
        return depAmtDue;
    }

    /**
     * Sets the value of the depAmtDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepAmtDue(String value) {
        this.depAmtDue = value;
    }

    /**
     * Gets the value of the depRecvDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepRecvDt() {
        return depRecvDt;
    }

    /**
     * Sets the value of the depRecvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepRecvDt(String value) {
        this.depRecvDt = value;
    }

    /**
     * Gets the value of the optPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptPrice() {
        return optPrice;
    }

    /**
     * Sets the value of the optPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptPrice(String value) {
        this.optPrice = value;
    }

    /**
     * Gets the value of the balanceDueDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceDueDt() {
        return balanceDueDt;
    }

    /**
     * Sets the value of the balanceDueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceDueDt(String value) {
        this.balanceDueDt = value;
    }

    /**
     * Gets the value of the balanceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceAmt() {
        return balanceAmt;
    }

    /**
     * Sets the value of the balanceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceAmt(String value) {
        this.balanceAmt = value;
    }

    /**
     * Gets the value of the balanceRecvDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceRecvDt() {
        return balanceRecvDt;
    }

    /**
     * Sets the value of the balanceRecvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceRecvDt(String value) {
        this.balanceRecvDt = value;
    }

    /**
     * Gets the value of the totTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotTax() {
        return totTax;
    }

    /**
     * Sets the value of the totTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotTax(String value) {
        this.totTax = value;
    }

    /**
     * Gets the value of the cancelFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelFee() {
        return cancelFee;
    }

    /**
     * Sets the value of the cancelFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelFee(String value) {
        this.cancelFee = value;
    }

    /**
     * Gets the value of the totAmtDue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotAmtDue() {
        return totAmtDue;
    }

    /**
     * Sets the value of the totAmtDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotAmtDue(String value) {
        this.totAmtDue = value;
    }

    /**
     * Gets the value of the agncyCommission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgncyCommission() {
        return agncyCommission;
    }

    /**
     * Sets the value of the agncyCommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgncyCommission(String value) {
        this.agncyCommission = value;
    }

}
