//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NumAdults"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NumChild"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NumRooms"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BIC"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}RateAccess"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}RoomType"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}NumBeds"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}BedType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numAdults",
    "numChild",
    "numRooms",
    "bic",
    "rateAccess",
    "roomType",
    "numBeds",
    "bedType"
})
@XmlRootElement(name = "TypeRQual")
public class TypeRQual
    implements Serializable
{

    @XmlElement(name = "NumAdults", required = true)
    protected String numAdults;
    @XmlElement(name = "NumChild", required = true)
    protected String numChild;
    @XmlElement(name = "NumRooms", required = true)
    protected String numRooms;
    @XmlElement(name = "BIC", required = true)
    protected String bic;
    @XmlElement(name = "RateAccess", required = true)
    protected String rateAccess;
    @XmlElement(name = "RoomType", required = true)
    protected String roomType;
    @XmlElement(name = "NumBeds", required = true)
    protected String numBeds;
    @XmlElement(name = "BedType", required = true)
    protected String bedType;

    /**
     * Gets the value of the numAdults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumAdults() {
        return numAdults;
    }

    /**
     * Sets the value of the numAdults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumAdults(String value) {
        this.numAdults = value;
    }

    /**
     * Gets the value of the numChild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumChild() {
        return numChild;
    }

    /**
     * Sets the value of the numChild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumChild(String value) {
        this.numChild = value;
    }

    /**
     * Gets the value of the numRooms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumRooms() {
        return numRooms;
    }

    /**
     * Sets the value of the numRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumRooms(String value) {
        this.numRooms = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIC(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the rateAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateAccess() {
        return rateAccess;
    }

    /**
     * Sets the value of the rateAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateAccess(String value) {
        this.rateAccess = value;
    }

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomType(String value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the numBeds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumBeds() {
        return numBeds;
    }

    /**
     * Sets the value of the numBeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumBeds(String value) {
        this.numBeds = value;
    }

    /**
     * Gets the value of the bedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBedType() {
        return bedType;
    }

    /**
     * Sets the value of the bedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBedType(String value) {
        this.bedType = value;
    }

}
