//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.31 at 11:27:25 AM ICT 
//


package com.galileoindonesia.schema.pnr;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}SpclCondInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}PFInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AirV"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Fare"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}RTInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FIC"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Class"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}AP"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}APEndItem"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Validity"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}OutInInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}Seasons"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}MileOrRte"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}GlobInd"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}DayTmRests"/>
 *         &lt;element ref="{http://www.galileoindonesia.com/schema/PNR}FareCabinClsSeg"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spclCondInd",
    "pfInd",
    "airV",
    "fare",
    "rtInd",
    "fic",
    "clazz",
    "ap",
    "apEndItem",
    "validity",
    "outInInd",
    "seasons",
    "mileOrRte",
    "globInd",
    "dayTmRests",
    "fareCabinClsSeg"
})
@XmlRootElement(name = "Type1Qual")
public class Type1Qual
    implements Serializable
{

    @XmlElement(name = "SpclCondInd", required = true)
    protected String spclCondInd;
    @XmlElement(name = "PFInd", required = true)
    protected String pfInd;
    @XmlElement(name = "AirV", required = true)
    protected String airV;
    @XmlElement(name = "Fare", required = true)
    protected String fare;
    @XmlElement(name = "RTInd", required = true)
    protected String rtInd;
    @XmlElement(name = "FIC", required = true)
    protected String fic;
    @XmlElement(name = "Class", required = true)
    protected String clazz;
    @XmlElement(name = "AP", required = true)
    protected String ap;
    @XmlElement(name = "APEndItem", required = true)
    protected String apEndItem;
    @XmlElement(name = "Validity", required = true)
    protected String validity;
    @XmlElement(name = "OutInInd", required = true)
    protected String outInInd;
    @XmlElement(name = "Seasons", required = true)
    protected String seasons;
    @XmlElement(name = "MileOrRte", required = true)
    protected String mileOrRte;
    @XmlElement(name = "GlobInd", required = true)
    protected String globInd;
    @XmlElement(name = "DayTmRests", required = true)
    protected String dayTmRests;
    @XmlElement(name = "FareCabinClsSeg", required = true)
    protected String fareCabinClsSeg;

    /**
     * Gets the value of the spclCondInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclCondInd() {
        return spclCondInd;
    }

    /**
     * Sets the value of the spclCondInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclCondInd(String value) {
        this.spclCondInd = value;
    }

    /**
     * Gets the value of the pfInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPFInd() {
        return pfInd;
    }

    /**
     * Sets the value of the pfInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPFInd(String value) {
        this.pfInd = value;
    }

    /**
     * Gets the value of the airV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirV() {
        return airV;
    }

    /**
     * Sets the value of the airV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirV(String value) {
        this.airV = value;
    }

    /**
     * Gets the value of the fare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFare() {
        return fare;
    }

    /**
     * Sets the value of the fare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFare(String value) {
        this.fare = value;
    }

    /**
     * Gets the value of the rtInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRTInd() {
        return rtInd;
    }

    /**
     * Sets the value of the rtInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRTInd(String value) {
        this.rtInd = value;
    }

    /**
     * Gets the value of the fic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIC() {
        return fic;
    }

    /**
     * Sets the value of the fic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIC(String value) {
        this.fic = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the ap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAP() {
        return ap;
    }

    /**
     * Sets the value of the ap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAP(String value) {
        this.ap = value;
    }

    /**
     * Gets the value of the apEndItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPEndItem() {
        return apEndItem;
    }

    /**
     * Sets the value of the apEndItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPEndItem(String value) {
        this.apEndItem = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidity(String value) {
        this.validity = value;
    }

    /**
     * Gets the value of the outInInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutInInd() {
        return outInInd;
    }

    /**
     * Sets the value of the outInInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutInInd(String value) {
        this.outInInd = value;
    }

    /**
     * Gets the value of the seasons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeasons() {
        return seasons;
    }

    /**
     * Sets the value of the seasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeasons(String value) {
        this.seasons = value;
    }

    /**
     * Gets the value of the mileOrRte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMileOrRte() {
        return mileOrRte;
    }

    /**
     * Sets the value of the mileOrRte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMileOrRte(String value) {
        this.mileOrRte = value;
    }

    /**
     * Gets the value of the globInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobInd() {
        return globInd;
    }

    /**
     * Sets the value of the globInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobInd(String value) {
        this.globInd = value;
    }

    /**
     * Gets the value of the dayTmRests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayTmRests() {
        return dayTmRests;
    }

    /**
     * Sets the value of the dayTmRests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayTmRests(String value) {
        this.dayTmRests = value;
    }

    /**
     * Gets the value of the fareCabinClsSeg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareCabinClsSeg() {
        return fareCabinClsSeg;
    }

    /**
     * Sets the value of the fareCabinClsSeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareCabinClsSeg(String value) {
        this.fareCabinClsSeg = value;
    }

}
